//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficeClass
    {
        public int Id { get; set; }
        public string OfficeName { get; set; }
        public string Extension { get; set; }
        public string Division { get; set; }
        public string Department { get; set; }
    }
}
